const fleetData = [
  {
    id: 1,
    name: "Swift Dzire",
    category: "Reliable City Sedan",
    price: 2499,
    seats: 4,
    luggage: 3,
    ac: true,
    image: "/images/swift-dzire.jpg",
    type: "Luxury",
  },
  {
    id: 2,
    name: "Maruti Ertiga",
    category: "Premium Family MPV",
    price: 3200,
    seats: 6,
    luggage: 4,
    ac: true,
    image: "/images/ertiga.jpg",
    type: "GroupTravel",
  },
   {
    id: 3,
    name: "Toyota etios ",
    category: "Premium Family MPV",
    price: 6000,
    seats: 6,
    luggage: 4,
    ac: true,
    image: "/images/etios.jpg",
    type: "Executive",
  },
   {
    id: 4,
    name: "Toyota innova",
    category: "Premium Family MPV",
    price: 6500,
    seats: 6,
    luggage: 4,
    ac: true,
    image: "/images/innova.jpg",
    type:"GroupTravel" ,
  },
   {
    id: 5,
    name: "Toyota crysta",
    category: "Premium Family MPV",
    price: 3200,
    seats: 6,
    luggage: 4,
    ac: true,
    image: "/images/crysta.jpg",
    type: "Luxury"
  },
   {
    id: 6,
    name: "Tempo Traveller",
    category: "Premium Family MPV",
    price: 12000,
    seats: 6,
    luggage: 4,
    ac: true,
    image: "/images/tempo.jpg",
    type: "GroupTravel"
  },
];

export default fleetData;